Vanilla psykal version
arporter/NEMO-DSL pull request #5
Opened 2017-02-10 22:49 UTC by rupertford

All relevant code (within the timestep loop) has been turned into kernels with the iteration space moved into a manual PSy layer. I think we are therefore ready to merge. Andy, could you take a look.

I needed to make one change to the original code to get bit reproducibility but I think it is fair to call this a fix to a bug. Silvia, could you check you are happy with this

Note, we are not yet at the stage where Andy can think about extending the existing gocean infrastructure to support 3d as there are a number of issues that need discussing. I've written the next set of issues that I am aware of as a discussion in #4.

2017-02-13 20:44 UTC, arporter commented
I can build and run the code so that's good. Silvia has also said that she's happy with the bug fix.
I'll consider the code changes next.

2017-02-13 20:46 UTC, arporter commented on src/psykal/Makefile
> +# Makefile for the original form of the tra_adv benchmark.
This should say it is for the PSyKAl form of the benchmark.

2017-02-13 20:46 UTC, arporter commented on src/psykal/Makefile
> +#   export OMPFLAGS=-fopenmp
OMPFLAGS and MPIF90 are not required for this code. Please remove.

2017-02-13 21:02 UTC, arporter commented on src/psykal/psy.f90
> +    DO jk = 1, jpk-1
Loop bounds match those in original code. However that then means that the kernel updates points on (ji,jj,jk+1).

2017-02-13 21:06 UTC, arporter commented on src/psykal/zwx2_kern.f90
> +    zwx(ji,jj,jk+1) = pwn(ji,jj,jk+1) * ( zalpha * zzwx + (1.-zalpha) * zzwy )
As noted earlier, this kernel writes to location (ji,jj,jk+1) rather than (ji,jj,jk).

2017-02-13 21:28 UTC, arporter commented on src/psykal/zero_kern_mod.f90
> +  subroutine zero_kern_2d(field,jj,ji)
AFAICS, this routine isn't used anywhere. Has it been superseded by `zero_layer()`?

2017-02-13 21:36 UTC, arporter requested changes
I think this is mostly fine as a first step. I'd like to see it without the `jpi,jpj,jpk` being passed all the time but we can do that once we've agreed in #4.

Please address the comments about un-used code and the Makefile.
Please also add a README.md that very briefly says what this code is and how to build and run it. I know it's a pain but better to get at least something in now that we can add to later.

2017-02-13 22:50 UTC, rupertford commented on src/psykal/Makefile
> +# Makefile for the original form of the tra_adv benchmark.
Agreed. 'tis now changed.

2017-02-13 22:50 UTC, rupertford commented on src/psykal/Makefile
> +#   export OMPFLAGS=-fopenmp
Agreed. 'tis now changed.

2017-02-13 22:58 UTC, rupertford commented on src/psykal/psy.f90
> +    DO jk = 1, jpk-1
Yes indeed. I left it as-is for the timebeing and raised it as something to discuss in ticket #4

2017-02-13 23:00 UTC, rupertford commented on src/psykal/zwx2_kern.f90
> +    zwx(ji,jj,jk+1) = pwn(ji,jj,jk+1) * ( zalpha * zzwx + (1.-zalpha) * zzwy )
Yes indeed. I left it this way for the timebeing (i.e. as written in the original code) and raised it in issue #4

2017-02-13 23:01 UTC, rupertford commented on src/psykal/zero_kern_mod.f90
> +  subroutine zero_kern_2d(field,jj,ji)
Yes, well spotted. I've removed it.

2017-02-13 23:15 UTC, rupertford commented
Suggested changes have been made. Time for second review.

2017-02-14 11:29 UTC, arporter approved these changes

2017-02-14 11:30 UTC, arporter commented
All looks good now. This pull request can be merged.

2017-02-14 11:52 UTC, merged